trigger: none
pr: none

parameters:
- name: vsoDeployerBuildID
  type: string
  default: "master"

variables:
- template: vars.yml

jobs:
- job: Mirror_images
  pool:
    name: ARO-CI

  steps:
  - template: ./templates/template-setup-golang-env.yml
    parameters:
      gobin: ${{ variables.GOBIN }}
      gopath: ${{ variables.GOPATH }}
      goroot: ${{ variables.GOROOT }}
      modulePath: ${{ variables.modulePath }}
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project: $(vso-project-id)
      pipeline: $(vso-deployer-pipeline-id)
      ${{ if eq(parameters.vsoDeployerBuildID, 'master') }}:
        buildVersionToDownload: latestFromBranch
        branchName: refs/heads/master
      ${{ if ne(parameters.vsoDeployerBuildID, 'master') }}:
        buildVersionToDownload: specific
        buildId: ${{ parameters.vsoDeployerBuildID }}
      downloadType: specific
      downloadPath: $(System.ArtifactsDirectory)/deployer
    displayName: Download Deployer
  - template: ./templates/template-mirror-images.yml
    parameters:
      dstAuth: $(acr-push-auth)
      srcAuthGeneva: $(acr-geneva-pull-auth)
      srcAuthQuay: $(quay-pull-auth)
      dstACRName: $(dst-acr-name)
      deployerDirectory: $(System.ArtifactsDirectory)/deployer/drop
